import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  AudioWaveform,
  BadgeAlert,
  Camera,
  ChevronsLeftRight,
  CircleCheckBig,
  CircleStop,
  Clapperboard,
  Cog,
  Disc3,
  Eye,
  EyeOff,
  Grid3x3,
  Hand,
  Headphones,
  Image,
  Info,
  Laptop,
  LayoutGrid,
  Mic,
  MicOff,
  Monitor,
  MonitorPlay,
  MousePointerClick,
  Pause,
  PanelLeft,
  PanelRight,
  PanelsTopLeft,
  PanelTop,
  Play,
  Radio,
  RotateCcw,
  RotateCw,
  ScanEye,
  Settings,
  ShieldAlert,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Speaker,
  Sparkles,
  Square,
  TabletSmartphone,
  TriangleAlert,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  Webcam,
  Wrench,
  Zap,
  type LucideProps,
} from "lucide-react";

import type { WebdeckIconName } from "./types";

const iconMap: Record<WebdeckIconName, (props: LucideProps) => JSX.Element> = {
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "audio-lines": AudioLines,
  "audio-waveform": AudioWaveform,
  "badge-alert": BadgeAlert,
  camera: Camera,
  "chevrons-left-right": ChevronsLeftRight,
  mic: Mic,
  "mic-off": MicOff,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  video: Video,
  "video-off": VideoOff,
  webcam: Webcam,
  eye: Eye,
  "eye-off": EyeOff,
  "scan-eye": ScanEye,
  radio: Radio,
  play: Play,
  pause: Pause,
  square: Square,
  "circle-stop": CircleStop,
  "disc-3": Disc3,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  clapperboard: Clapperboard,
  monitor: Monitor,
  "monitor-play": MonitorPlay,
  image: Image,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  cog: Cog,
  wrench: Wrench,
  "layout-grid": LayoutGrid,
  "panels-top-left": PanelsTopLeft,
  "panel-top": PanelTop,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  laptop: Laptop,
  "tablet-smartphone": TabletSmartphone,
  smartphone: Smartphone,
  "mouse-pointer-click": MousePointerClick,
  hand: Hand,
  headphones: Headphones,
  speaker: Speaker,
  sparkles: Sparkles,
  zap: Zap,
  "triangle-alert": TriangleAlert,
  "circle-check-big": CircleCheckBig,
  info: Info,
  "shield-alert": ShieldAlert,
  "grid-3x3": Grid3x3,
};

export function LucideIcon({
  name,
  ...props
}: LucideProps & { name: WebdeckIconName }) {
  const Icon = iconMap[name];
  return <Icon {...props} />;
}
